# ansible-playbook -C -i /path/to/ansible_hosts -l hostname(s) file.yml
---
- name: centralize sso logs
  hosts: sso
  become: yes
  become_user: root
  become_method: sudo
  vars:
    # be sure you have a :vars in your hosts.yml that sets ldap_env_type.  We use dev, test or "".
    short_hostname: "{{ inventory_hostname | regex_replace('^([^.]*?)[.].*', '\\1') }}"
    rsyslog_work_dir: "/var/log/rsyslogWorkDirectory"
  tasks:
    # http://www.tomcatexpert.com/knowledge-base/rotating-catalinaout-log-files
    - name: install epel
      yum:
        name: epel-release
        state: present
    - name: install cronolog
      yum:
        name: cronolog
        state: present
    - name: update catalina.sh
      replace:
        path: /opt/apache-tomcat/bin/catalina.sh
        regexp: '>> "\$CATALINA_OUT" 2>&1 "&"'
        replace: '2>&1 | /usr/sbin/cronolog "$CATALINA_BASE/logs/catalina-%Y-%m-%d.out" &'
        backup: yes
    - name: create rsyslog working directory
      file:
        path: "{{ rsyslog_work_dir }}"
        state: directory
    - name: update client rsyslog.conf
      template:
        src: sso_rsyslog.conf.j2
        dest: /etc/rsyslog.conf
        mode: 0644
        backup: yes
      register: rsyslogconf_updated
    - name: restart client rsyslog
      service: name=rsyslog state=restarted
      when: rsyslogconf_updated.changed
    - name: update server rsyslog.conf
      blockinfile:
        dest: /etc/rsyslog.conf
        insertbefore: "/var/log/catchall.log"
        backup: yes
        block: |
          :syslogtag, isequal,  "{{ env_type }}ssocatalina" /var/log/sso/catalina{{ env_type }}
          &~
        marker: "# {mark} ANSIBLE MANAGED BLOCK {{ env_type }}sso"
      register: server_rsyslogconf_updated
      delegate_to: "{{ rsyslog_server }}"
    - name: restart server rsyslog
      service: name=rsyslog state=restarted
      when: server_rsyslogconf_updated.changed
      delegate_to: "{{ rsyslog_server }}"
