# ansible-playbook -C -i /path/to/ansible_hosts -l hostname(s) file.yml
---
- name: centralize ldap logs
  hosts: centosldap
  become: yes
  become_user: root
  become_method: sudo
  vars:
    ldap_env_type: "{{ inventory_hostname | regex_replace('^([^l]+?)l.*', '\\1') }}"
  tasks:
    - name: update client rsyslog.conf
      template:
        src: directory_rsyslog.conf.j2
        dest: /etc/rsyslog.conf
        mode: 0644
        backup: yes
    - name: update server rsyslog.conf
      blockinfile:
        dest: /etc/rsyslog.conf
        insertbefore: "/var/log/catchall.log"
        backup: yes
        block: |
          :syslogtag, isequal,  {{ ldap_env_type }}diraccess /var/log/dirsrv/access
          &~
          :syslogtag, isequal,  {{ ldap_env_type }}direrrors /var/log/dirsrv/errorprd
          &~
          :syslogtag, isequal,  {{ ldap_env_type }}diraudit /var/log/dirsrv/auditprd
          &~
      register: server_rsyslogconf_updated
      delegate_to: "{{ rsyslog_server }}"
