# ansible-playbook -C -i /path/to/ansible_hosts -l hostname(s) file.yml
---
- name: centralize ldap logs
  hosts: centosldap
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - include: tasks/ldap_log_entry.yml 
      with_items:
        - "access"
        - "errors"
        - "audit"
      loop_control:
        loop_var: log_name
    - name: restart rsyslogd
      service: name=rsyslog state=restarted
      when: rsyslogconf_updated.changed
