# ansible-playbook -i /path/to/directory_hosts -l ldap1.domain.net  install_389.yml
# for example:
#     ansible-playbook -C -i ../sdp_ansible_cf/hosts.yml -l hostname  install_389.yml
# if you want to reinstall, uninstall 389 on the host(s) first: ds_removal  -s ldap1 -w pass 
---
- name: prep to install 389 directory server
  hosts: 389ldap # there are additional plays below: update this below if you change it here
  become: yes
  become_user: root
  become_method: sudo
  vars:
    use_existing_mc: 1
    config_for_mc: no
  tasks:
    - name: install epel packages
      yum:
        name: epel-release
        state: present
        update_cache: yes
    - name: install 389 packages
      yum:
        name: 389-ds
        state: present
        update_cache: yes
    - name: enable directory
      systemd:
        name: dirsrv.target
        enabled: yes
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
    - name: enable directory admin
      systemd:
        name: dirsrv-admin
        enabled: yes
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
    - name: set sysctl.conf
      sysctl:
        name: "{{ item.thing }}"
        value: "{{ item.value }}"
        ignoreerrors: yes
      with_items:
        - { thing: 'net.ipv4.tcp_keepalive_time', value: '300' }
        - { thing: 'fs.file-max', value: '64000' }
      register: reboot
    - name: update limits.conf
      lineinfile: dest=/etc/security/limits.conf line="{{ item }}"
      with_items:
        - "*	-	nofile	8192"
        - "nobody               soft        nofile          4096"
        - "nobody               hard        nofile          63536"
        - "nobody      soft      nproc      2047"
        - "nobody      hard      nproc      16384"
      register: reboot
    - include: tasks/reboot.yml
    - name: check if 389 DS is installed
      stat: path=/etc/dirsrv/slapd-{{ ansible_hostname }}
      register: installdir
    - name: selinux getsebool work-around for setup-ds-admin.pl
      # https://fedorahosted.org/389/ticket/377 
      lineinfile: dest=~/bin/getsebool create=yes mode=0755 line="{{ item }}"
      with_items:
        - "#!/bin/sh"
        - "echo on"
        - "exit 0"
      when: installdir.stat.exists is defined and installdir.stat.exists == False
    - name: selinux setsebool work-around for setup-ds-admin.pl
      lineinfile: dest=~/bin/setsebool create=yes mode=0755 line="{{ item }}"
      with_items:
        - "#!/bin/sh"
        - "echo on"
        - "exit 0"
      when: installdir.stat.exists is defined and installdir.stat.exists == False
    - name: selinux semanage work-around for setup-ds-admin.pl
      lineinfile: dest=~/bin/semanage create=yes mode=0755 line="{{ item }}"
      with_items:
        - "#!/bin/sh"
        - "echo on"
        - "exit 0"
      when: installdir.stat.exists is defined and installdir.stat.exists == False
    - name: set naming_value, used in install inf
      set_fact: naming_value="{{ ansible_domain | regex_replace("\..*", "") }}"
    - name: set current fqdn for conditonals below
      set_fact:
        current_fqdn: "{{ansible_hostname}}.{{ansible_domain}}"
    - name: set current fqdn, used to set a few variables in install inf
      set_fact: use_existing_mc=0
      when:
        - current_fqdn == config_dir_host
    - name: set config_for_mc, used in install inf
      set_fact: config_for_mc=no
      when:
        - current_fqdn == config_dir_host
    - name: generate 389 install inf
      template: src=templates/389_install.inf.j2 dest=/var/tmp/389_{{ ansible_hostname }}.inf mode=0600
      when: installdir.stat.exists is defined and installdir.stat.exists == False
      # if this is not here during a clean install with a .inf the installer will not install the configs on a central server
    - name: generate adm.conf
      template: 
        src: templates/adm.conf.j2
        dest: /etc/dirsrv/admin-serv/adm.conf
      when: installdir.stat.exists is defined and installdir.stat.exists == False

- name: run 389 installer serially
  hosts: 389ldap
  become: yes
  become_user: root
  become_method: sudo
  serial: 1
  tasks:
    - name: check if 389 DS is installed
      stat: path=/etc/dirsrv/slapd-{{ ansible_hostname }}
      register: installdir
    - name: install 389 directory
      command: setup-ds-admin.pl -s -f /var/tmp/389_{{ ansible_hostname }}.inf
      async: 0
      poll: 0
      ignore_errors: true
      when: installdir.stat.exists is defined and installdir.stat.exists == False
      register: cat
    - debug: var=cat.stdout_lines
      when: cat.stdout_lines is defined

- name: post install
  hosts: 389ldap
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: delete 389 install inf
      file:
        path: /var/tmp/389_{{ ansible_hostname }}.inf
        state: absent
    - name: create ssl password file
      template:
        src: templates/389_pin.txt.j2
        dest: /etc/dirsrv/slapd-{{ ansible_hostname }}/pin.txt
        mode: 0600
