# ansible-playbook -C -i /path/to/ansible_hosts -l hostname(s) file.yml
---
- name: reboot hosts
  hosts: enterpriseldap
  become: yes
  become_user: root
  become_method: sudo
  vars:
    manualreboot: 1
  tasks:
    - include: tasks/reboot.yml
