# ansible-playbook -C -i /path/to/ansible_hosts -l hostname(s) file.yml
---
- name: delete all vmware snashot(s)
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: set vm_snap_state to remove_all
      set_fact:
        vm_snap_state: remove_all
    - include: tasks/vm_snapshot.yml
