# ansible-playbook -C -i /path/to/ansible_hosts -l hostname(s) -e vm_snap_name=testsnap vm_snapshot_create.yml
# ansible-playbook -C -i /path/to/ansible_hosts -l hostname(s) vm_snapshot_create.yml

---
- name: yum update
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: set vm_snap_state to present
      set_fact:
        vm_snap_state: present
    - include: tasks/vm_snapshot.yml
