# ansible-playbook -C -i /path/to/ansible_hosts -l hostname(s) -e vm_snap_name=testsnap vm_snapshot_delete.yml
# ansible-playbook -C -i /path/to/ansible_hosts -l hostname(s) vm_snapshot_delete.yml
---
- name: delete vmware snapshot(s)
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: set vm_snap_state to remove_all
      set_fact:
        vm_snap_state: absent
    - include: tasks/vm_snapshot.yml
