# ansible-playbook -C -i /path/to/ansible_hosts -l hostname(s) file.yml
---
- name: update client rsyslog conf
  lineinfile: dest=/etc/rsyslog.conf line="{{ item }}" backup=yes
  with_items:
    - "$InputFileName /var/log/dirsrv/slapd-{{ inventory_hostname | regex_replace('^([^.]*?)[.]', '\\1.') }}/{{ log_name }}"
    - "$InputFileTag {{ inventory_hostname | regex_replace('^([^l]+?)l.*', '\\1') }}dir{{ log_name }}"
    - "$InputFileStateFile stats_dir{{ log_name }}"
    - "$InputFileSeverity info"
    - "$InputFileFacility local5"
    - "$InputRunFileMonitor"
    - "local5.* @@{{ rsyslog_server_mgmt }}:10514"
  register: rsyslogconf_updated
- name: update server rsyslog.conf
  lineinfile: dest=/etc/rsyslog.conf line="{{ item }}" insertbefore="*.*\s+/var/log/catchall.log" backup=yes
  with_items:
    - ":syslogtag, isequal, \"prddiracc\" /var/log/dirsrv/auditprd"
    - "&~"
  register: server_rsyslogconf_updated
  delegate_to: "{{ rsyslog_server }}"
