# ansible-playbook -C -i /path/to/ansible_hosts -l hostname(s) file.yml
---
- name: update client rsyslog conf
  blockinfile:
    dest: /etc/rsyslog.conf
    backup: yes
    block: |
      $InputFileName /var/log/dirsrv/slapd-{{ inventory_hostname | regex_replace('^([^.]*?)[.].*', '\1') }}/{{ log_name }}
      $InputFileTag {{ inventory_hostname | regex_replace('^([^l]+?)l.*', '\1') }}dir{{ log_name }}
      $InputFileStateFile stats_dir{{ log_name }}
      $InputFileSeverity info
      $InputFileFacility local5
      $InputRunFileMonitor
      local5.* @@{{ rsyslog_server_mgmt }}:10514

      
  register: rsyslogconf_updated
- name: update server rsyslog.conf
  blockinfile:
    dest: /etc/rsyslog.conf
    insertbefore: "/var/log/catchall.log"
    backup: yes
    block: |
      :syslogtag, isequal, "prddiracc" /var/log/dirsrv/auditprd
      &~
  register: server_rsyslogconf_updated
  delegate_to: "{{ rsyslog_server }}"
